### ISSUE TITLE
Cannot generate citations for report or thesis using APA csl

### ISSUE THREAD

**Issue by MatthewRichardsonICPSR** [michel-kraemer/citeproc-java#36] opened 2017-05-18 13:23 UTC
I'm using citeproc-java to generate citations with the APA 6th edition stylesheet. (https://github.com/citation-style-language/styles/blob/master/apa.csl) It fails when I attempt to create a display citation for report or thesis. I'm using version 1.0.1 of citeproc-java.

It's not clear to me if the error is with citeproc-java or with the CSL; the MLA CSL  (https://github.com/citation-style-language/styles/blob/master/modern-language-association.csl) works just fine, but then again, the APA CSL works for other ref types. 

When I attempt to build the display citation via

CSL.makeAdhocBibliography(APA_6THED, cslItemData).makeString()

I get an error message that begins with:

2017-05-18 09:08:37.649:WARN:oejs.ServletHandler:qtp261518457-17: 
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalArgumentException: Could not make bibliography

The key parts seems to be:

Caused by: 
de.undercouch.citeproc.script.ScriptRunnerException: Could not call method
	at de.undercouch.citeproc.script.JREScriptRunner.callMethod(JREScriptRunner.java:108)

Caused by: 
javax.script.ScriptException: TypeError: Cannot read property "slice" from undefined in <eval> at line number 808
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:467)

Caused by: 
<eval>:808 TypeError: Cannot read property "slice" from undefined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)

I can paste the full stacktrace if it would help.

In trying to resolve the bug, I went through the APA CSL to see if there was a mandatory element that I needed in order to get it to work. I added edition, version, collection title, number, container title, url, and doi, beyond the core elements: author, title, publisher, publisher place, issued. That didn't fix the issue. 

I then tried a more minimalist approach and tried removing everything I could, but that produced the same error.

CSLItemDataBuilder builder = new CSLItemDataBuilder();
builder.title("Sample report title");
builder.type(CSLType.REPORT);
builder.publisher("ICPSR");
builder.publisherPlace("Ann Arbor, MI");
CSLName name = new CSLName("Richardson", "Matthew", null, null, null, null, null, null, null, null, null, null);
CSLName[] authors = new CSLName[1];
authors[0] = name;
builder.author(authors);
int[] dateParts = new int[]{2017,5,1};
int[][] datePartsArray = new int[1][3];
datePartsArray[0] = dateParts;
CSLDate date = new CSLDate(datePartsArray, null, null, null, null);
builder.issued(date);
CSLItemData cslItemData = builder.build();
return CSL.makeAdhocBibliography(APA_6THED, cslItemData).makeString();

Any assistance you can provide is greatly appreciated.

**Comment by MatthewRichardsonICPSR** [comment] 2017-09-21 13:59
To follow up on this, I've been able to demonstrate the same error with the GLOSSA stylesheet, but not MLA.

https://github.com/citation-style-language/styles/blob/master/glossa.csl
https://github.com/citation-style-language/styles/blob/master/apa.csl
https://github.com/citation-style-language/styles/blob/master/modern-language-association.csl

**Comment by michel-kraemer** [comment] 2018-05-20 12:02
I cannot reproduce the issue - even with the example code you provided. Which version of citeproc-java are you using?

**Comment by michel-kraemer** [comment] 2018-05-20 12:03
By the way, I'm using Java 8 with Nashorn as JavaScript interpreter and not Rhino. Maybe that's the problem?

**Comment by michel-kraemer** [comment] 2018-05-20 12:06
Sorry, I just read that you're using citeproc-java 1.0.1. Please try again with 1.1.0-SNAPSHOT. I think it's high time I release a new version :smile:

**Comment by MatthewRichardsonICPSR** [comment] 2018-05-21 12:03
This makes me very happy. I eventually tracked down the problem to an issue in citeproc.js. I resolved that with fbennett in that project around the end of Nov. 2017. So citeproc.js version 1.1.181 corrects the bug I encountered. What version of citeproc.js is used in the new version of citeproc-java?

**Comment by michel-kraemer** [comment] 2018-05-21 12:13
I upgraded to 1.1.206 yesterday. :smile:

**Comment by MatthewRichardsonICPSR** [comment] 2018-06-25 14:43
I'm sorry to pester you, but I can't seem to get the fix to work. When I use maven to pull in version 1.0.1, I get CSL that has a processor version of 1.1.137, not 1.1.206. I did delete the package from my local drive so that it would re-download it, but I'm not getting a version with 1.1.206.

Are you planning to increment the version of citeproc-java to reflect the change?

**Comment by gallardo** [comment] 2019-10-07 15:03
You can set the exact version in the build.gradle: https://github.com/michel-kraemer/citeproc-java/blob/1d5bf0e7bbb2bdc47309530babf0ecaba838bf10/citeproc-java/build.gradle#L18-L19

You can see in my PR an example: https://github.com/michel-kraemer/citeproc-java/blob/55492a803e8b1f972ea26693fef7e7902e507a3f/citeproc-java/build.gradle#L18-L19.

**Comment by michel-kraemer** [comment] 2019-11-06 18:57
A new version will be released in a few days (most likely on the weekend). I will close the issue now. Please open a new one if you still experience the problem with the new version.

**Closed by michel-kraemer** 2019-11-06 18:57 UTC
