### ISSUE TITLE
Exception on 

### ISSUE THREAD

**Issue by gduh** [michel-kraemer/citeproc-java#24] opened 2015-08-14 12:56 UTC
Hi,

I get the following exception : 

*javax.script.ScriptException: <eval>:59:4 Expected an operand but found default*
    *default xml namespace = "http://purl.org/net/xbiblio/csl"; with({});*
    *^ in <eval> at line number 59 at column number 4*

when I try your sample code from your web site : http://michel-kraemer.github.io/citeproc-java/using/getting-started/

It raises from CSL.class on : *runner.loadScript(getClass().getResource("xmle4x.js"));*

Thks for your help
Gregory

**Comment by apurde** [comment] 2015-08-20 01:18
Hi Gregory,

are you using Rhino as JS engine? I also got an exception in that area (however a different one) when running the 0.6 release with the JS engine provided with Java.

Remark: the latest source code on git closed my exception

Andreas

**Comment by gduh** [comment] 2015-08-20 07:09
Hi Andreas,

I'm not using Rhino but the engine provided by JRE 7. Do you think it could solve the issue ?

Until now I used Maven, but I'm going to try to use directly the latest source code in order to check if it changes something or not.

**Comment by apurde** [comment] 2015-08-20 09:13
Yes I think it will solve the problem. You have two options: 1) use Rhino as JS engine or 2) use the latest sources and build your jar locally. I recommend to use 1) as the performance of the standard engine is terrible. I tried it ;-)

**Comment by gduh** [comment] 2015-08-20 15:09
it's ok now using rhino and if the performance is best it's even better !
Thanks for your help.

**Comment by michel-kraemer** [comment] 2015-09-13 07:59
Great! So the issue is solved. I'll close it.

**Closed by michel-kraemer** 2015-09-13 07:59 UTC
