### ISSUE TITLE
Additional Output formats

### ISSUE THREAD

**Issue by dominic01** [michel-kraemer/citeproc-java#50] opened 2018-06-18 11:57 UTC
You already have "html", "text", "asciidoc", "fo", and "rtf". Just wondering if we can add another one "xml" to this list.

Output Bibliography: APA
`Friedl, J. E. F. (2006). Mastering Regular Expressions (3rd ed.). O’Reilly Media.`

I am expecting a tagged output like:
`<aus><au>Friedl, J. E. F.</au></aus>. (<dt>2006</dt>). <ti>Mastering Regular Expressions</ti> (<et>3rd ed.</et>). <pu>O’Reilly Media</pu>.`

Is it possible to get additional tagged output format like above. The elements could be any and standard.

**Comment by michel-kraemer** [comment] 2018-06-19 20:43
With an output format you can only control the visual appearance of a citation or bibliography, but you don't have access to semantic information (i.e. you can't differentiate between title, author, year, etc.). For this, you need to create your own style.

This issue is a duplicate of https://github.com/Juris-M/citeproc-js/issues/72. Let's continue the discussion there.

**Closed by michel-kraemer** 2018-06-19 20:43 UTC
