### ISSUE TITLE
Support for et-al-min et-al-use-first in pure Java snapshot

### ISSUE THREAD

**Issue by tweverett** [michel-kraemer/citeproc-java#101] opened 2021-03-25 20:01 UTC
It seems that the pure Java snapshot does not support authors truncation. For example, with apa (https://github.com/citation-style-language/styles/blob/master/apa.csl), when the reference has more than two authors, the in-text citation should list only the first author followed by et al. Using the pure Java snapshot, there's no truncation. All authors are listed. I'd be grateful if you could help fix this or point me in the right direction. Thanks!

**Comment by mdoering** [comment] 2021-06-18 13:25
The issue still persists, so please don't close it. @michel-kraemer any chance for a quick fix?
The native java version is performing so much better, it would be a shame to revert to an older version because of this.

**Closed** 2021-06-19 10:27 UTC
Labels: pinned

**Comment by michel-kraemer** [comment] 2021-06-19 10:28
@tweverett @mdoering Sorry for the long delay! The issue should be fixed in the latest snapshot. Please test and let me know if it still doesn't work. Thanks for your support!

**Comment by mdoering** [comment] 2021-06-21 13:03
Excellent, the latest snapshot works now as expected!

**Comment by aysegulozkaya** [comment] 2021-07-12 08:09
> Excellent, the latest snapshot works now as expected!

Hello, the problem still persists for me. IEEE format works correctly, but APA, MLA, BibTex formats still show all of the authors. I have 3.0.0 citeproc java and 21.4 snapshots of styles. What should I do? Thank you.

**Comment by michel-kraemer** [comment] 2021-07-12 08:39
@aysegulozkaya Please open a new issue and provide the citation data, the expected output, and the actual output so I can reproduce the issue. Thanks.

**Comment by aysegulozkaya** [comment] 2021-07-12 08:54
> @aysegulozkaya Please open a new issue and provide the citation data, the expected output, and the actual output so I can reproduce the issue. Thanks.

Thank you. I opened the issue https://github.com/michel-kraemer/citeproc-java/issues/107
