### ISSUE TITLE
Field locator not mapped

### ISSUE THREAD

**Issue by walterMPDL** [michel-kraemer/citeproc-java#29] opened 2016-06-30 13:40 UTC
it seems like the field locator is not mapped

**Comment by michel-kraemer** [comment] 2016-07-20 05:45
I'd be surprised if it wasn't. Could you please send me a small reproducer?

**Comment by walterMPDL** [comment] 2016-07-21 12:35
This is the CSL-XML for a reproduction:
`<?xml version="1.0" encoding="utf-8"?>
<style class="in-text" version="1.0" demote-non-dropping-particle="sort-only" default-locale="de" xmlns="http://purl.org/net/xbiblio/csl">
  <info>
    <title>LocatorTest</title>
    <id>http://www.zotero.org/styles/LocatorTest</id>
    <updated>2016-07-20T13:29:57+00:00</updated>
  </info>
  <locale xml:lang="de">
    <terms>
      <term name="chapter" form="short">ch.</term>
      <term name="presented at">presented at the</term>
      <term name="available at">available</term>
    </terms>
  </locale>
  <macro name="author">
    <names variable="author">
      <name initialize-with=". " delimiter=", " and="text"/>
      <label form="short" prefix=", " text-case="capitalize-first"/>
      <substitute>
        <names variable="editor"/>
        <names variable="translator"/>
      </substitute>
    </names>
  </macro>
  <macro name="editor">
    <names variable="editor">
      <name initialize-with=". " delimiter=", " and="text"/>
      <label form="short" prefix=", " text-case="capitalize-first"/>
    </names>
  </macro>
  <citation collapse="citation-number">
    <sort/>
    <layout delimiter=", "/>
  </citation>
  <bibliography entry-spacing="0" second-field-align="flush">
    <layout suffix=".">
      <text macro="author" suffix=", "/>
      <text variable="title"/>
      <text variable="locator" prefix="(" suffix=")"/>
    </layout>
  </bibliography>
</style>
`
It's just about the bibliography. If you need the code, we use for simple testing: 
https://github.com/MPDL-Collections/PubMan/tree/master/common_services/tools/csl_testing
start the main method in the executor with the argument "http://dev-pubman.mpdl.mpg.de/cone/citation-styles/resource/citation-styles48912" (this is where we uploaded the style for testing)

**Comment by michel-kraemer** [comment] 2016-07-24 15:05
I debugged the code and everything is forwarded correctly. I then tested your style with the Visual Editor [1] and could not see the locator either. AFAICT locators are only supported in citations and not in a bibliography. citeproc-java supports this if you set the `CSLCitationItem` correctly:

```java
List<Citation> cs = citeproc.makeCitation(new CSLCitation(new CSLCitationItemBuilder("1234").locator("A locator").build()));
for (Citation c : cs) {
    System.out.println(c.getText());
    // => Müller, Fischer, A nice little article, 2016, S. A locator.
}
```

Of course you also have to add a `<citation>` element to your style to make this work.

```xml
<citation collapse="citation-number">
	<layout delimiter="; " suffix=".">
		<group delimiter=", ">
			<names variable="author">
				<name form="short"/>
			</names>
			<text variable="title"/>
			<group delimiter=" ">
				<label form="short" strip-periods="false" variable="locator"/>
				<number variable="locator"/>
			</group>
		</group>
	</layout>
</citation>
```

I hope this helps. Let me know if this resolves your issue.

Cheers,
Michel

[1] http://editor.citationstyles.org/visualEditor/

**Comment by michel-kraemer** [comment] 2016-07-31 12:54
I'm closing this issue because I think it's solved. If you still have problems and want to discuss it further feel free to open the issue again.

**Closed by michel-kraemer** 2016-07-31 12:54 UTC

**Comment by walterMPDL** [comment] 2016-08-01 06:37
I'm sorry for answering so late. Your response made clear, why it didn't work. It isn't solving our problem, as we are working with the bibilography only, but we will find a workaround. But is there a reason, why locator is not mapped in the biblography?

**Comment by michel-kraemer** [comment] 2016-08-01 07:29
I don't know actually. As I said everything is forwarded correctly. It might be an issue with citeproc-js. You should post the question on their mailing list.

Note that in citeproc-java we're using citeproc-js 1.0.521 and the latest version is 1.1.71 so it might be that the issue is already fixed and we just need to update the library. But this is something that the citeproc-js folks may be able to confirm.

**Comment by walterMPDL** [comment] 2016-08-01 07:34
Thanks for all the help. I will have a look at the new citeproc-js version. When I can get some more information, I will give you feedback.
