### ISSUE TITLE
Get List of Supported Styles

### ISSUE THREAD

**Issue by damionx7** [michel-kraemer/citeproc-java#182] opened 2022-12-19 19:50 UTC
Thanks for this wonderful library. I want to get list of supported styles. Is this possible ?

I can see that there is a method `CSL.getSupportedStyles()` but it gives me zero styles.

**Comment by michel-kraemer** [comment] 2023-01-22 06:57
Which version of citeproc-java are you using? Did you make sure, the styles are on your classpath (artifact `org.citationstyles:styles:23.1`)?

**Comment by damionx7** [comment] 2023-01-22 07:18
Hey. I am using the latest alpha version and have included styles library. 

Btw I am on android.

**Comment by michel-kraemer** [comment] 2023-01-22 07:31
🤔 I've never tested the library on android. That might be the problem. The source code of `getSupportedStyles()` is here: https://github.com/michel-kraemer/citeproc-java/blob/master/citeproc-java/src/main/java/de/undercouch/citeproc/CSL.java#L289-L291

It calls `getAvailableFiles`, which in turn tries to find the ieee style on the classpath. From this, it derives the location of the jar file containing the styles and lists all its entries. It might be that this code does not work on Android. If you know how to fix it, pull requests are welcome!

**Comment by michel-kraemer** [comment] 2023-03-10 07:08
I suppose this is a duplicate of #191. Please follow up there, or comment here if you think this is incorrect. Thanks.

**Closed by michel-kraemer** 2023-03-10 07:08 UTC
Labels: enhancement
