### ISSUE TITLE
aci-materials-journal citation style: incorrect formatting of pages info

### ISSUE THREAD

**Issue by PrimoQA** [michel-kraemer/citeproc-java#149] opened 2022-04-28 11:19 UTC
**Describe the bug**
When citing an item having pages range/ start page - end page, e.g. journal article, aci-materials-journal CSL style assumes quoting pages in a shortened format while as structured within the version 3.0.0-alpha.2 it appears in full.

Please fill in the following sections and provide as much information as possible. It will help us to reproduce the issue. Leave sections blank or remove them if they don't apply.

**Which version of citeproc-java are you using?**
1.0.1

**Expected behavior**
Expected citation structure us as below:

 
    1.Hisakata, R., Nishida, S., and Johnston, A. “An Adaptable Metric Shapes Perceptual Space,” Current biology, V. 26, No. 14, 2016, pp. 1911–5.
 

**Actual behavior**

  
    1.Hisakata, R., Nishida, S., and Johnston, A. “An Adaptable Metric Shapes Perceptual Space,” Current biology, V. 26, No. 14, 2016, pp. 1911–1915. - please note that pages info appears in full instead of being in a shortened format.
  

**CSL input**
 CSL api object fields: {"id":"-GEN-181h5kgumb","type":"article-journal","language":"eng","author":[{"family":"Hisakata","given":"Rumi"},{"family":"Nishida","given":"Shin&#8217;ya"},{"family":"Johnston","given":"Alan"}],"issued":{"date-parts":[[2016]]},"container-title":"Current biology","DOI":"10.1016\/j.cub.2016.05.047","edition":"","ISBN":"","ISSN":"0960-9822","issue":"14","keyword":"Adaptation, Physiological ; Form Perception ; Humans ; Motion Perception ; Photic Stimulation ; Report ; Retina - physiology","note":"","number-of-pages":"","page":"1911-1915","page-first":"1911-1915","PMID":"27426520","publisher":"Elsevier Ltd","publisher-place":"England","section":"","title":"An Adaptable Metric Shapes Perceptual Space","URL":"","volume":"26"}

**Used style and locale**
aci-materials-journal

**Rendered output/Screenshots**
If applicable, add the output that citeproc-java produced and/or screenshots to help explain your problem.

**Example code/unit test**
Provide example code or a unit test to reproduce your issue. You may also insert a link to your repository containing a minimal reproducer here.

**Comment by michel-kraemer** [comment] 2022-05-01 13:56
Duplicate of #148

**Closed by michel-kraemer** 2022-05-01 13:56 UTC
Labels: bug
