### ISSUE TITLE
CSL capitalisations

### ISSUE THREAD

**Issue by bwychan** [michel-kraemer/citeproc-java#203] opened 2023-04-06 00:31 UTC
I have found a bug in the CSLs such that some records have first letter capitalisations or all caps in the title. 

I am using the following CSL in our PrimoVE instance (Murdoch University, Australia):
- apa-cv
- chicago-author-date
- chicago-note-bibliography
- modern-language-association
- australian-guide-to-legal-citation
- vancouver
- american-chemical society
- ieee

Both books and articles are affected. The examples below are in APA, but I also checked them in the other citation styles and in most of them, the capitalisation of the title seems to be consistent and inherited from the source data (especially the all caps one). 

Fisher, A. D., April, M. D., Naylor, J. F., Kotwal, R. S., & Schauer, S. G. (2021). The Battalion Aid Station—The Forgotten Frontier of the Army Health System During the Global War on Terrorism. Military Medicine. [https://doi.org/10.1093/milmed/usab401](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1093%2Fmilmed%2Fusab401&data=05%7C01%7Cb.chan%40murdoch.edu.au%7C42371589e6d9427ddf2e08db35a94ea6%7Cc00d4c1bcf7b4e93b7c710113a9bc230%7C1%7C0%7C638162773530527459%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gvlOyb0eA8mY3kajje%2B4MnPs5%2FBOr798Zau7BFBZqYE%3D&reserved=0) 
[https://librarysearch.murdoch.edu.au/permalink/61MUN_INST/3bciql/cdi_proquest_miscellaneous_2582809655](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flibrarysearch.murdoch.edu.au%2Fpermalink%2F61MUN_INST%2F3bciql%2Fcdi_proquest_miscellaneous_2582809655&data=05%7C01%7Cb.chan%40murdoch.edu.au%7C42371589e6d9427ddf2e08db35a94ea6%7Cc00d4c1bcf7b4e93b7c710113a9bc230%7C1%7C0%7C638162773530527459%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ghHgV3WxEV2kGNF8D%2Fztl86X0eLzJiNYsJFEU%2FUkY3E%3D&reserved=0) 

Melanson, M., & Bower, M. (2011). THE ROLE OF THE ARMY NUCLEAR MEDICAL SCIENCE OFFICER IN THE GLOBAL WAR ON TERRORISM. Health Physics (1958), 101(1), S78–S78. 
[https://librarysearch.murdoch.edu.au/permalink/61MUN_INST/3bciql/cdi_proquest_miscellaneous_902382635](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flibrarysearch.murdoch.edu.au%2Fpermalink%2F61MUN_INST%2F3bciql%2Fcdi_proquest_miscellaneous_902382635&data=05%7C01%7Cb.chan%40murdoch.edu.au%7C42371589e6d9427ddf2e08db35a94ea6%7Cc00d4c1bcf7b4e93b7c710113a9bc230%7C1%7C0%7C638162773530527459%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4hkLPbdlDIcD2jiyxoOM7fzvUGVFaf4nuj9G08DQjMg%3D&reserved=0) 

Moore, A. (2019). Empire’s Labor The Global Army That Supports U.S. Wars. Cornell University Press. [https://doi.org/10.7591/9781501716393](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.7591%2F9781501716393&data=05%7C01%7Cb.chan%40murdoch.edu.au%7C42371589e6d9427ddf2e08db35a94ea6%7Cc00d4c1bcf7b4e93b7c710113a9bc230%7C1%7C0%7C638162773530527459%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=q8McVW%2Bzm7RlPSMhm0lTEIDf6O%2BIQP5Uqbu%2FdxoPuLs%3D&reserved=0) 
[https://librarysearch.murdoch.edu.au/permalink/61MUN_INST/1r6on8i/alma991005438684007891](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flibrarysearch.murdoch.edu.au%2Fpermalink%2F61MUN_INST%2F1r6on8i%2Falma991005438684007891&data=05%7C01%7Cb.chan%40murdoch.edu.au%7C42371589e6d9427ddf2e08db35a94ea6%7Cc00d4c1bcf7b4e93b7c710113a9bc230%7C1%7C0%7C638162773530684123%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=o9oM9Obyugb5abPdppazHFWLECMvav7zmwchRpGeJJc%3D&reserved=0) 

Ramos, B., Miller, F. A., Brandão, T. R. S., Teixeira, P., & Silva, C. L. M. (2013). Fresh fruits and vegetables—An overview on applied methodologies to improve its quality and safety. Innovative Food Science & Emerging Technologies, 20, 1–15. [https://doi.org/10.1016/j.ifset.2013.07.002](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1016%2Fj.ifset.2013.07.002&data=05%7C01%7Cb.chan%40murdoch.edu.au%7C42371589e6d9427ddf2e08db35a94ea6%7Cc00d4c1bcf7b4e93b7c710113a9bc230%7C1%7C0%7C638162773530684123%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hy0oZ6pGtjKvna1UBX0yUZU8ZfeWJtb8k4OUB1QCo%2Fc%3D&reserved=0) 

Schneid, F. C. (2012). The projection and limitations of imperial powers, 1618-1850. Brill. 
[https://librarysearch.murdoch.edu.au/permalink/61MUN_INST/1r6on8i/alma991005511866207891](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flibrarysearch.murdoch.edu.au%2Fpermalink%2F61MUN_INST%2F1r6on8i%2Falma991005511866207891&data=05%7C01%7Cb.chan%40murdoch.edu.au%7C42371589e6d9427ddf2e08db35a94ea6%7Cc00d4c1bcf7b4e93b7c710113a9bc230%7C1%7C0%7C638162773530684123%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3%2BqGvaoPAddoPMGLxMWSRthOpelQQruh7mnCEFVQS20%3D&reserved=0) 

For example, in APA, only the first letter of a title/subtitle should be capitalised, as well as proper nouns. However, as can be seen, there is a variety of outputs which indicates that the capitalisation script does not seem to be working consistently. In particular, for the last one on the list, the APA citation has only the first word capitalise, but the other styles (Chicago etc.) have every word capitalised.

I am not sure which version of citeproc-java is being used, but was referred here by Ex Libris. But you should be able to test in our live PrimoVE environment without a login as the citation system is open to the public.

Regards,

Bryan Chan
Librarian, Digital Applications
Library and Knowledge Services
Murdoch University

**Comment by michel-kraemer** [comment] 2023-04-19 07:08
The APA style does not specify any text-case attribute for the title. You can see that yourself if you look at the source code and search for `variable="title"`:
https://github.com/citation-style-language/styles/blob/master/apa.csl
None of the occurrences contain a `text-case` attribute. This means that citeproc-java will not do any text transformation and the title will be used as is.

I've double-checked this with Zotero, which can generate a citation preview for various styles. Here's the result:

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/295407/232992338-d87efecc-e846-4139-af1f-8a4d8c624ea5.png">

As you can see, even in Zotero the title is used as is.

I'm closing this issue as it is not a bug. A proper title-case algorithm has already been implemented in the latest version of citeproc-java and it will be applied if there is a `text-case` attribute defined in the style. If you still experience problems with other styles, I recommend updating. The latest version works correctly according to the CSL specification.

**Closed by michel-kraemer** 2023-04-19 07:08 UTC
Labels: bug
